age=input("Enter your age: ")
print(int(age)+5)

str1=("string")
num1=(32)
num2=(32.45)
Name=("Saba")
Age=10
list1=(1, 2)
num3=(3.5)
surname= ("Kuridze")
month=(3)
height=(1.5)
bank_name=("Bazis Bank")
bank_storage=(120567430.30)
lamp_cost=(12)
lamp_colour=("blue")
car_cost=(50000)
num4=(12.34)
car_name=("Mazda")
mazda_cost=(40000)
mazda_panting_cost=(120.5)
list2=(3, 4)

print(type(str1))
print(type(num1))
print(type(num2))
print(type(Name))
print(type(Age))
print(type(list1))
print(type(num3))
print(type(surname))
print(type(month))
print(type(height))
print(type(bank_name))
print(type(bank_storage))
print(type(lamp_cost))
print(type(lamp_colour))
print(type(car_cost))
print(type(num4))
print(type(car_name))
print(type(mazda_cost))
print(type(mazda_panting_cost))
print(type(list2))

print (int ("66"))
print (int ("56"))
print (int ("46"))
print (int ("36"))
print (int ("26"))
print (int ("16"))
print (int ("96"))
print (int ("86"))
print (int ("69"))
print (int ("68"))

print (str (69))
print (str (68))
print (str (67))
print (str (66))
print (str (65))
print (str (64))
print (str (63))
print (str (62))
print (str (61))
print (str (60))

print (float (30))
print (float (31))
print (float (32))
print (float (33))
print (float (34))
print (float (35))
print (float (36))
print (float (37))
print (float (38))
print (float (39))